### ISSUE TITLE
Suggestion for interesting facts below search bar

### ISSUE THREAD

**Issue by kanishka8276** [sairish2001/makesmatheasy.github.io#43]
We can create a list of around 15 interesting facts which are visible turn by turn below the search bar when the user is not connected to internet instead of showing "Turn on internet connection to read some interesting facts".
#GsSOC'21

**Comment by kanishka8276** [comment]
Please assign this to me.

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any.

Actually the message you are seeing, on the top I.e. **Turn on your internet connection, to read interesting facts.**  is due to mixed content. API is of `http://` protocol and main website is of `https://` protocol that's why it's not able to call API.

By the I liked your Idea, i.e to make array of Facts and display them. I would Like to say kindly increase number 15 to __some greater to increase the list

**Comment by kanishka8276** [comment]
Yes sure! I will create an array with more number of amazing facts.
Thank you for assigning!
